version: '3.8'
services:
  db:
    image: postgres
    container_name: postgresDb
    restart: always
    volumes:
      - ./chameleon/db_setup:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPass
    ports:
      - '5432:5432'