name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: make install-requirements
      
      - name: Run tests
        run: make run-test
